--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/mxnkr/Pictures/IMG_2366.png"

-- Special
background="#000000"
foreground="#f6f6f5"
cursor="#f6f6f5"

-- Colors
color0="#000000"
color1="#ACC5E0"
color2="#B1CDEB"
color3="#E8C0BC"
color4="#CCD8E9"
color5="#D6E7F5"
color6="#FCFCCA"
color7="#f6f6f5"
color8="#acacab"
color9="#ACC5E0"
color10="#B1CDEB"
color11="#E8D5D3"
color12="#CCD8E9"
color13="#D6E7F5"
color14="#F3F8FC"
color15="#f6f6f5"
